- id: trivyfs-docker
  name: trivyfs-docker
  entry: aquasec/trivy:0.48.1 fs --cache-dir /src/.pre-commit-trivy-cache --exit-code 1
  language: docker_image
  pass_filenames: false

- id: trivyconfig-docker
  name: trivyconfig-docker
  entry: aquasec/trivy:0.48.1 config --cache-dir /src/.pre-commit-trivy-cache --exit-code 1
  language: docker_image
  pass_filenames: false
